fix: a parsing error for JavaScript SVGO configuration files
Update the call to the "eval" package [1] to provide a (dummy) filename
in order to prevent TypeError, specifically:

    .../svgo-action/node_modules/eval/eval.js:38
      var _filename = filename || module.parent.filename;
                                                ^
    TypeError: Cannot read properties of undefined (reading 'filename')

By providing a filename explicitly, the or (`||`) is shortcircuited and
hence the error is prevented. By preventing the error, parsing the SVGO
JavaScript configuration works again.

--
1. https://www.npmjs.com/package/eval